# Eggs.Variant
#
# Copyright Agustin K-ballo Berge, Fusion Fenix 2014-2016
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

os:
  - Visual Studio 2013
  - Visual Studio 2015

configuration:
  - Debug
  - Release

branches:
  only:
    - master
    - develop
    - explicit

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config %CONFIG%
